balance_strategy: class_weights
batch_size: 64
classifier_dropout: 0.43456715291826387
classifier_hidden: 32
classifier_layers: 3
cnn_base_channels: 48
cnn_layers: 3
discriminator_hidden: 64
discriminator_layers: 1
domain_loss_weight: 0.35725220536260527
domain_weight_schedule: exponential
focal_gamma: 3.075919213258973
gamma_grl: 6.990186331855127
learning_rate: 0.0004543120746370023
lr_scheduler: step
lstm_bidirectional: true
lstm_dropout: 0.2060165554717562
lstm_hidden: 256
lstm_layers: 2
use_attention: true
use_residual: false
warmup_epochs: 10
weight_decay: 7.22739740940809e-05
